/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import Function.ShortestPath;

/**
 *
 * @author GOCCHAN
 */
public class Home extends javax.swing.JFrame {
    
    private double[][] data = new double[][]{};
    private ShortestPath sp = new ShortestPath();
    
    /**
     * Creates new form Home
     */
    
    private int selectNodeStart=-1,selectNodeEnd=-1; //sesuatu yang dibutuhkan untuk mendapatkan apakah sudah terpilih node start atau akhirnya
    private JButton buttStart=null, buttEnd=null;
    
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        setAllColorDefault();
    }
    
    public void setAllColorDefault(){
        butt_0.setBackground(Color.white);
        butt_1.setBackground(Color.white);
        butt_2.setBackground(Color.white);
        butt_3.setBackground(Color.white);
        butt_4.setBackground(Color.white);
        butt_5.setBackground(Color.white);
        butt_6.setBackground(Color.white);
        butt_7.setBackground(Color.white);
        butt_8.setBackground(Color.white);
        butt_9.setBackground(Color.white);
        butt_10.setBackground(Color.white);
        butt_11.setBackground(Color.white);
        butt_12.setBackground(Color.white);
        butt_13.setBackground(Color.white);
        butt_14.setBackground(Color.white);
        butt_15.setBackground(Color.white);
        butt_16.setBackground(Color.white);
        butt_17.setBackground(Color.white);
        butt_18.setBackground(Color.white);
        butt_19.setBackground(Color.white);
        butt_20.setBackground(Color.white);
        butt_21.setBackground(Color.white);
        butt_22.setBackground(Color.white);
        butt_23.setBackground(Color.white);
        startText.setText("-");
        endText.setText("-");
    }
    /** SelectedButton :
     * Jika start belum dipilih, set start node
     * Jika start sudah ada, set end node
     * Jika start node = node dipilih. maka, node start -1 (unselect)
     * @param node
     * @param butt
    */
    public void selectedButton(int node, JButton butt){
        if(selectNodeStart==-1){
            if(selectNodeEnd==node){
                buttEnd.setBackground(Color.white);
                selectNodeEnd=-1;
            }else{
                selectNodeStart=node;
                buttStart=butt;
                butt.setBackground(Color.green);
            }
        }else{
            if(selectNodeStart==node){
                selectNodeStart=-1;
                buttStart=null;
                butt.setBackground(Color.white);
            }else if(selectNodeEnd==node){
                selectNodeEnd=-1;
                buttEnd=null;
                butt.setBackground(Color.white);
            }else{
                System.out.println("in1");
                if(buttEnd!=null){
                    buttEnd.setBackground(Color.white);
                }
                buttEnd=butt;
                butt.setBackground(Color.red);
                selectNodeEnd=node;
            }
        }
        
        
        if(selectNodeStart==-1){
            startText.setText("-");
        }else{
            startText.setText(String.valueOf(selectNodeStart));
            
        }
        if(selectNodeEnd==-1){
            endText.setText("-");
        }else{
            endText.setText(String.valueOf(selectNodeEnd));
        }
    }
    
    public void setMatrix(double data[][])
    {
        this.data = data;
    }
    
    private void finalAction()
    {
        try {
            int start = Integer.parseInt(startText.getText());
            int finish = Integer.parseInt(endText.getText());
            System.out.println(start + " " + finish);
            for(int i=0; i<data.length; i++)
            {
                for(int j=0; j<data.length; j++)
                {
                    System.out.print(data[i][j] + " ");
                }
                System.out.println("");
            }
            //sp.shortestPath(data, start, finish);
            String result = "Min : " + sp.getMin() + "\n" +
                            "Path : " + sp.getPath().toString();
            System.out.println(result);
            resultField.setText(result);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Something Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        butt_1 = new javax.swing.JButton();
        butt_0 = new javax.swing.JButton();
        butt_2 = new javax.swing.JButton();
        butt_3 = new javax.swing.JButton();
        butt_4 = new javax.swing.JButton();
        butt_5 = new javax.swing.JButton();
        butt_6 = new javax.swing.JButton();
        butt_7 = new javax.swing.JButton();
        butt_19 = new javax.swing.JButton();
        butt_8 = new javax.swing.JButton();
        butt_9 = new javax.swing.JButton();
        butt_10 = new javax.swing.JButton();
        butt_11 = new javax.swing.JButton();
        butt_12 = new javax.swing.JButton();
        butt_13 = new javax.swing.JButton();
        butt_14 = new javax.swing.JButton();
        butt_15 = new javax.swing.JButton();
        butt_16 = new javax.swing.JButton();
        butt_17 = new javax.swing.JButton();
        butt_18 = new javax.swing.JButton();
        butt_20 = new javax.swing.JButton();
        butt_21 = new javax.swing.JButton();
        butt_22 = new javax.swing.JButton();
        butt_23 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        startText = new javax.swing.JTextField();
        endText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        butt_check = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultField = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butt_1.setText("1");
        butt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_1ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 50, 30));

        butt_0.setText("0");
        butt_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_0ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 50, 30));

        butt_2.setText("2");
        butt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_2ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 50, 30));

        butt_3.setText("3");
        butt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_3ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 50, 20));

        butt_4.setText("4");
        butt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_4ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 50, 30));

        butt_5.setText("5");
        butt_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_5ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 50, 30));

        butt_6.setText("6");
        butt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_6ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 50, 30));

        butt_7.setText("7");
        butt_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_7ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 50, 30));

        butt_19.setText("19");
        butt_19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_19ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 50, 30));

        butt_8.setText("8");
        butt_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_8ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 50, 30));

        butt_9.setText("9");
        butt_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_9ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 50, 30));

        butt_10.setText("10");
        butt_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_10ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 50, 30));

        butt_11.setText("11");
        butt_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_11ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 50, 30));

        butt_12.setText("12");
        butt_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_12ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, 30));

        butt_13.setText("13");
        butt_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_13ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 30));

        butt_14.setText("14");
        butt_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_14ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, 30));

        butt_15.setText("15");
        butt_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_15ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, 30));

        butt_16.setText("16");
        butt_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_16ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, 30));

        butt_17.setText("17");
        butt_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_17ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, 30));

        butt_18.setText("18");
        butt_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_18ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, 30));

        butt_20.setText("20");
        butt_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_20ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, 30));

        butt_21.setText("21");
        butt_21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_21ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, -1, 30));

        butt_22.setText("22");
        butt_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_22ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, 30));

        butt_23.setText("23");
        butt_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_23ActionPerformed(evt);
            }
        });
        getContentPane().add(butt_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/test.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        startText.setEditable(false);
        startText.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        startText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        startText.setText("-1");
        getContentPane().add(startText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 110, 50));

        endText.setEditable(false);
        endText.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        endText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        endText.setText("-1");
        getContentPane().add(endText, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 650, 110, 50));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("END NODE :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, -1, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("START NODE :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, -1, -1));

        butt_check.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        butt_check.setText("CHECK SHORTEST PATH");
        butt_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_checkActionPerformed(evt);
            }
        });
        getContentPane().add(butt_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 220, 80));

        jScrollPane1.setEnabled(false);

        resultField.setEditable(false);
        resultField.setColumns(20);
        resultField.setRows(5);
        resultField.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(resultField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 710, 490, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butt_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_0ActionPerformed
        selectedButton(Integer.parseInt(butt_0.getText()), butt_0);
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_0ActionPerformed

    private void butt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_1ActionPerformed
        selectedButton(Integer.parseInt(butt_1.getText()), butt_1);
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_1ActionPerformed

    private void butt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_2ActionPerformed
        selectedButton(Integer.parseInt(butt_2.getText()), butt_2);
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_2ActionPerformed

    private void butt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_3ActionPerformed
        selectedButton(Integer.parseInt(butt_3.getText()), butt_3);
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_3ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void butt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_4ActionPerformed
        selectedButton(Integer.parseInt(butt_4.getText()), butt_4);
// TODO add your handling code here:
    }//GEN-LAST:event_butt_4ActionPerformed

    private void butt_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_5ActionPerformed
        selectedButton(Integer.parseInt(butt_5.getText()), butt_5);
// TODO add your handling code here:
    }//GEN-LAST:event_butt_5ActionPerformed

    private void butt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_6ActionPerformed
        selectedButton(Integer.parseInt(butt_6.getText()), butt_6);
    // TODO add your handling code here:
    }//GEN-LAST:event_butt_6ActionPerformed

    private void butt_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_7ActionPerformed
        selectedButton(Integer.parseInt(butt_7.getText()), butt_7);
// TODO add your handling code here:
    }//GEN-LAST:event_butt_7ActionPerformed

    private void butt_19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_19ActionPerformed
        selectedButton(Integer.parseInt(butt_19.getText()), butt_19);
// TODO add your handling code here:
    }//GEN-LAST:event_butt_19ActionPerformed

    private void butt_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_8ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_8.getText()), butt_8);
    }//GEN-LAST:event_butt_8ActionPerformed

    private void butt_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_9ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_9.getText()), butt_9);
    }//GEN-LAST:event_butt_9ActionPerformed

    private void butt_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_10ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_10.getText()), butt_10);
    }//GEN-LAST:event_butt_10ActionPerformed

    private void butt_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_11ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_11.getText()), butt_11);
    }//GEN-LAST:event_butt_11ActionPerformed

    private void butt_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_12ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_12.getText()), butt_12);
    }//GEN-LAST:event_butt_12ActionPerformed

    private void butt_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_13ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_13.getText()), butt_13);
    }//GEN-LAST:event_butt_13ActionPerformed

    private void butt_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_14ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_14.getText()), butt_14);
    }//GEN-LAST:event_butt_14ActionPerformed

    private void butt_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_15ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_15.getText()), butt_15);
    }//GEN-LAST:event_butt_15ActionPerformed

    private void butt_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_16ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_16.getText()), butt_16);
    }//GEN-LAST:event_butt_16ActionPerformed

    private void butt_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_17ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_17.getText()), butt_17);
    }//GEN-LAST:event_butt_17ActionPerformed

    private void butt_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_18ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_18.getText()), butt_18);
    }//GEN-LAST:event_butt_18ActionPerformed

    private void butt_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_20ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_20.getText()), butt_20);
    }//GEN-LAST:event_butt_20ActionPerformed

    private void butt_21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_21ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_21.getText()), butt_21);
    }//GEN-LAST:event_butt_21ActionPerformed

    private void butt_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_22ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_22.getText()), butt_22);
    }//GEN-LAST:event_butt_22ActionPerformed

    private void butt_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_23ActionPerformed
        // TODO add your handling code here:
        selectedButton(Integer.parseInt(butt_23.getText()), butt_23);
    }//GEN-LAST:event_butt_23ActionPerformed

    private void butt_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_checkActionPerformed
        if(selectNodeStart==-1 || selectNodeEnd==-1){
            JOptionPane.showMessageDialog(this, "Tentukan titik awal dan akhir!");
        }else{
            //jika berhasil
            finalAction();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                double data[][] = new double[][]{{0, 0, 1.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.38, 0, 0, 0, 0, 0},
                                         {1.1, 0, 0, 0, 0, 0, 0.36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.68, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0.22, 0, 0, 0.45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.17, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0.22, 0, 0.41, 0, 0, 0, 0, 0, 0, 0, 0.99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0.41, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0.36, 0, 0, 0, 0, 0.55, 0.74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0.45, 0, 0, 0.55, 0, 0, 0, 0, 0.76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0, 0, 0.74, 0, 0, 0.59, 0, 0, 0, 0, 0.16, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0.59, 0, 0.36, 0, 0, 0, 0.78, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0.36, 0, 0.21, 0, 0, 0, 0.69, 0, 0, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0, 0, 0, 0.76, 0, 0, 0.21, 0, 0.48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.48, 0, 0.13, 0, 0, 0.52, 0, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0.99, 0, 0, 0, 0, 0, 0, 0, 0.13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.94, 0},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0.16, 0.78, 0, 0, 0, 0, 0, 0, 0, 0.85, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.69, 0, 0, 0, 0, 0, 0.32, 1.37, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.52, 0, 0, 0.32, 0, 0, 0, 0, 0.67, 0, 0, 0},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.85, 1.37, 0, 0, 0, 1.4, 0, 0, 0, 0},
                                         {0, 0.38, 0.68, 0.17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.4, 0, 0, 1, 0, 0, 1.5},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.67, 0, 0, 1, 0, 0.1, 0, 0},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0.62, 0.38},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.94, 0, 0, 0, 0, 0, 0, 0, 0.62, 0, 1},
                                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.5, 0, 0.38, 1, 0},
                                        };
                Home h = new Home();
                h.setMatrix(data);
                h.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butt_0;
    private javax.swing.JButton butt_1;
    private javax.swing.JButton butt_10;
    private javax.swing.JButton butt_11;
    private javax.swing.JButton butt_12;
    private javax.swing.JButton butt_13;
    private javax.swing.JButton butt_14;
    private javax.swing.JButton butt_15;
    private javax.swing.JButton butt_16;
    private javax.swing.JButton butt_17;
    private javax.swing.JButton butt_18;
    private javax.swing.JButton butt_19;
    private javax.swing.JButton butt_2;
    private javax.swing.JButton butt_20;
    private javax.swing.JButton butt_21;
    private javax.swing.JButton butt_22;
    private javax.swing.JButton butt_23;
    private javax.swing.JButton butt_3;
    private javax.swing.JButton butt_4;
    private javax.swing.JButton butt_5;
    private javax.swing.JButton butt_6;
    private javax.swing.JButton butt_7;
    private javax.swing.JButton butt_8;
    private javax.swing.JButton butt_9;
    private javax.swing.JButton butt_check;
    private javax.swing.JTextField endText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultField;
    private javax.swing.JTextField startText;
    // End of variables declaration//GEN-END:variables
}
